# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
require "base64"

default_platform(:android)

platform :android do
  desc "Runs a clean flutter build"
  lane :build_native_app do
    Dir.chdir "../.." do
      sh("npx", "react-native", "build-android", "--mode=release")
    end
  end

  desc "Build and upload to internal track"
  lane :internal do
    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges",
      between: ["origin/main", "HEAD"]
    )

    build_native_app

    supply(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_images: true, 
      skip_upload_screenshots: true
    )
  end

  desc "Promote version between tracks (ex.: internal -> production)"
  lane :promote do
    supply(
      from_track: ENV["FROM_TRACK"] || "internal",
      to_track: ENV["TO_TRACK"] || "production",
      rollout: (ENV["ROLLOUT"] || "1.0").to_f
    )
  end
end
